Add automatic lightline update
tsuyoshicho/lightline-lsp pull request #3
Opened 2022-12-25 13:20 UTC by a5ob7r

# Pull Request detail

## Related issues or PRs/関連issueやPR

None.

## Fix or Add/Remove in this PR/このプルリクエストでやったこと

- Add a boilerplate to update indicators

## Do not fix or add/remove this PR/このプルリクエストでやらなかったこと

None.

## Pros and Cons/メリットとデメリット

- Pros: We don't need to write a boilerplate to update indicators any more.
- Cons: Probably none.

## Test/動作確認

Test item list up with checkbox, checked after tested./チェックボックス式にし、確認後チェックする。

- [ ] Vim updates statusline contents (probably contain the indicators) when diagnostics complete.

2022-12-25 13:32 UTC, tsuyoshicho requested changes
@a5ob7r -san

Basically good.

However, if who have not installed `lightline` but have installed `vim-lsp` and `lightline-lsp`, there is a problem because it will call functions that do not exist.

It's better to have a small function (`s:update-lsp`) that checks if `lightline#update()` exists and only calls it if it does.

---

基本的には良いです。

ただ、`lightline` を導入していないが `vim-lsp` および `lightline-lsp` を導入してしまった場合、存在しない関数を呼ぶので問題があります。

小さい関数 (`s:update-lsp`) を作り、`lightline#update()` が存在するかチェックして、存在する場合だけ呼び出すようにしたほうがよいでしょう。

2022-12-25 14:39 UTC, a5ob7r commented
@tsuyoshicho 

Thank you for your review. I fixed the problem, but I made no function and made it inline instead because the function will be too small.

2022-12-26 01:03 UTC, tsuyoshicho approved these changes
LGTM
This is certainly enough.

2022-12-26 01:04 UTC, merged

2022-12-26 01:35 UTC, a5ob7r commented
Thank you.